server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 5000
          product-service:
            loggerLevel: BASIC

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - 'feign.FeignException$FeignClientException'
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

logging:
  level:
    ru.yandex.practicum.order.client.ProductClient: DEBUG
