CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0 AND reserved_quantity <= quantity),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_inventory_product_id UNIQUE (product_id)
);
