spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_analyzer
    username: dbuser
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: always

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
